platform :ios, '13.0'

target 'Japanese-Translator' do
  use_frameworks!


  target 'Japanese-TranslatorTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'Japanese-TranslatorUITests' do
    # Pods for testing
  end

end
